[package]
name = "zed_ember_language_server"
version = "0.0.1"
edition = "2021"
publish = false
license = "MIT"
authors = ["lougreenwood"]

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.6"
